GET http://localhost:3000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Yzg3ZGY4ZC0yNDU3LTRiN2QtYjE1ZC0xMmYzYTgxNjlkZjMiLCJlbWFpbCI6ImdvdWJhZGVzaXJlMEBnbWFpbC5jb20iLCJpYXQiOjE3ODY1NDk2NzQsImV4cCI6MTc4NzE1NDQ3NH0.rs772YY-oSHb19jE27vGHrSe2ZmQO-y33eAvIJpeQ94